rubygems/rubygems.github.io

_posts/2015-04-13-permadelete-on-yank.md

Blog post for https://github.com/rubygems/rubygems.org/pull/923
review @sferik @indirect @qrush @dwradcliffe 
This is the first draft. Blog post is small, I think we can keep it like that. 
Maybe add a FAQ ? not sure if it is necessary tho.

New yank behaviour blog post

---

_posts/2015-08-13-postmortem.md

Review please @andremedeiros @evanphx @qrush @skottler @indirect :smile:

add postmortem for Aug 10 2015

---

_posts/2015-02-15-2.4.6-released.md

Fix a typo

---

_posts/2018-02-15-2.7.6-released.md

This change is per the request of nmalkin, who worked jointly with David Fifield on this.

Add David Fifield to path traversal attribution per request of nmalkin

---

_posts/2018-03-09-rubygems-february-2018-updates.md
_posts/2018-04-09-rubygems-march-2018-updates.md

Took Feb 2018 monthly updates from the Ruby Together page and added it to the blog.

Created feb 2018 updates post

---

_posts/2018-07-12-rubygems-june-2018-updates.md
_posts/2018-07-14-rubygems-june-2018-updates.md

The June 2018 RubyGems blog post

Created June 2018 monthly update

---

_posts/2018-08-10-rubygems-july-2018-updates.md

July 2018 update blog post for RubyGems and RubyGems.org

Created the July monthly update blog post

---

_posts/2018-09-10-rubygems-august-2018-updates.md

Blog post recapping RG and RG dot org work in August

August monthly update blog post

---

_posts/2018-10-15-rubygems-september-2018-updates.md

September monthly update blog post

---

_posts/2018-11-05-october-2018-updates.md

Create October 2018 monthly update

---

_posts/2019-02-02-december-2018-updates.md

Blog post roundup for Dec 2018

Created dec 2018 monthly update

---

_posts/2019-03-05-security-advisories-2019-03.md

Fix some typos

---

_posts/2019-03-05-security-advisories-2019-03.md

This is requested by nyangawa.

Added reporter's affiliation.

---

_posts/2019-03-05-and-then-there-was-one-metadata-links.md

[Read with markdown formatting](https://gist.github.com/sonalkr132/8608c421ae1cf79623567a05a3bffaf0#file-and-then-there-was-one-md)
[metadata milestone](https://github.com/rubygems/rubygems.org/milestone/7)

Add blog for metadata links

---

.gitignore
_posts/2020-03-09-announcing-rubygems-stats.md

It's neat, check it out: https://stats.rubygems.org.

Announcing RubyGems.org Stats

---

_posts/2020-07-16-removing-sha1-passwords-in-rubygems-org.md

Written by @colby-swandale 
Edited by @indirect

Publish - Removing SHA1 passwords from RubyGems.org

---

_posts/2020-08-13-july-rubygems-update.md

Hi @indirect, I've got a draft for July's update kindly help review :)

Add July RubyGems Update

---

_posts/2020-10-15-september-rubygems-update.md

Update post and add some grammar corrections

Update September Monthly Blog

---

_posts/2020-04-27-march-rubygems-update.md
_posts/2020-10-15-september-rubygems-update.md
_posts/2020-11-16-october-rubygems-update.md

- Add October monthly update
- Minor grammar fixes

Add October Monthly Update

---

_posts/2021-03-12-february-rubygems-update.md

A first draft of the monthly update.
Hi, @deivid-rodriguez can you help me provide more context about the priority issue that got fixed and if there are any other updates you'll like to add to February's monthly.
@sonalkr132 can you also help review the RubyGems.org section. 
Thanks!

Add February Monthly Update

---

_posts/2021-04-07-march-rubygems-update.md

Hi, @deivid-rodriguez and @sonalkr132 can you help review the monthly updatE for March and also let me know if there's any additional update I need to add.
Thanks!

Add March 2021 RubyGems Updates

---

_posts/2021-05-11-april-rubygems-update.md

sorry, didn't notice this. point 4 is the same.

Remove duplicate update from post

---

_posts/2021-07-09-june-rubygems-updates.md

Monthly Updates Draft for RubyGems.
Hi, @deivid-rodriguez and @sonalkr132 can you help review this draft to make sure I covered important updates from June.

Add June RubyGems Updates Post

---

_posts/2021-08-09-july-rubygems-updates.md
_posts/2021-08-11-july-rubygems-updates.md

Hi, @sonalkr132 and @deivid-rodriguez can you help look through this update to ensure I captured the work done in July properly. thanks!

Add July Monthly Update Post

---

_posts/2021-11-09-october-rubygems-updates.md

Hi @deivid-rodriguez and @sonalkr132 👋🏽 
I have the draft for October ready can you please help review it to make sure I covered all the changes made in October.
Thank you!

Add October 2021 RubyGems Update

---

_posts/2021-12-07-november-rubygems-updates.md
_posts/2021-12-09-november-rubygems-updates.md

Hello, @sonalkr132 and @deivid-rodriguez got some time to help review my draft for work done in November?
If there's anything I'm missing or need to change please let me know thanks!

Add November Monthly Updates

---

_posts/2021-12-09-november-rubygems-updates.md

Add correct PR link to one of the updates.

Update Novemeber Update Post

---

_posts/2022-01-18-december-rubygems-updates.md

Hi, @deivid-rodriguez  and @sonalkr132 can you let me know what other updates I'm missing from last month's work. 
So far I only have one from each project.
Thanks.

Add RubyGems Update for December 2021

---

_posts/2022-02-08-january-rubygems-updates.md

Hi, @sonalkr132  and @deivid-rodriguez can you help me review last month's work to ensure I covered the important updates.
Thanks!

Add RubyGems Monthly Post

---

_posts/2022-03-04-february-rubygems-updates.md
_posts/2022-03-07-february-rubygems-updates.md

Hi @deivid-rodriguez can you help me review this draft to ensure I captured work done in February?
Thank you!

Add February RubyGems Update

---

_posts/2022-04-03-march-rubygems-updates.md

Draft for March monthly updates.
Hi @deivid-rodriguez, can you help review that I captured work done in March correctly thank you!

Add March RubyGems Updates

---

_posts/2022-04-03-march-rubygems-updates.md
_posts/2022-05-08-april-rubygems-updates.md

Draft for RubyGems Monthly Update.
Hi @deivid-rodriguez can you help review the RubyGems News section?

Add April Monthly Update

---

_posts/2022-07-08-june-rubygems-updates.md

Monthly RubyGems Update Draft.
Hi @deivid-rodriguez, can you help review the RubyGems updates included in this draft to make sure I captured work done correctly. thank you!

Add June RubyGems Update

---

_posts/2022-10-17-septemeber-rubygems-updates.md
_posts/2022-10-18-septemeber-rubygems-updates.md

RubyGems Update roundup for the month of September

Add September Monthly Update Post

---

_posts/2023-01-19-december-rubygems-updates.md

RubyGems update roundup for December 2022.
Hi @deivid-rodriguez, can you help review this month's update to ensure I accurately captured the work done last month?

Add Monthly RubyGems Update for December 2022

---

_posts/2023-02-16-january-rubygems-updates.md

Update RubyGems January Post

---

_posts/2023-03-11-february-rubygems-updates.md

Quick typo fix and added screenshot of admin dashboard

Update Feb Monthly Post

---

_posts/2023-04-11-security-device-cli-support.md

Fixes: https://github.com/rubygems/rubygems.org/issues/3710

Fix bundler slack link in WebAuthn CLI blog post

---

_posts/2023-05-17-april-rubygems-updates.md

RubyGems update roundup for April 2023.
Hi, @deivid-rodriguez, @hsbt, and @simi could you help review this month's update to ensure I accurately captured the work done last month?

Publish RubyGems Monthly Updates for April 2023

---

_posts/2023-06-14-may-rubygems-updates.md
_posts/2023-06-19-may-rubygems-updates.md

RubyGems update roundup for May 2023.
Hi, @deivid-rodriguez, @hsbt, and @simi could you help review this month's update to ensure I accurately captured the work done last month?

Publish May 2023 RubyGems Update

---

.github/workflows/build.yml
.travis.yml

Since the travis build is no longer working

Replace travis with github actions

---

_posts/2023-08-07-july-rubygems-updates.md
_posts/2023-08-11-july-rubygems-updates.md

RubyGems monthly update roundup

Add RubyGems Monthly Update for July 2023

---

_posts/2023-09-10-august-rubygems-updates.md
_posts/2023-09-19-august-rubygems-updates.md

RubyGems monthly update roundup for August 2023

Publish August 2023 RubyGems Monthly Update

---

_posts/2023-10-09-september-rubygems-updates.md
_posts/2023-10-17-september-rubygems-updates.md

Publish RubyGems Monthly Updates

---

_posts/2023-12-14-trusted-publishing.md

Closes https://github.com/rubygems/rubygems.github.io/issues/172

Add blog post announcing trusted publishing

---

_posts/2025-02-20-dealing-with-sham-packages.md

Signed-off-by: Samuel Giddins <segiddins@segiddins.me>

Q1 Alpha-Omega blog post

---

_posts/2025-03-20-introducing-new-policies.md

new blog post introducing the new policies for RubyGems.org

Introducing new policies

---

_posts/2025-07-08-policies-live.md

Add blog post announcing that the new policies are live on rubygems.org

Publish policies live post
