stylesheets/scss/_post.scss

This pull request add a new css rule for `article` to prevent overflow for unbreakable long string like SHA256.
Before
After
The post above is here: http://blog.rubygems.org/2015/06/08/2.4.8-released.html

Prevent overflow for unbreakable long string like SHA256

---

atom.xml

If post.title were to contain one of `&`, `<`, or `>`, the XML would become invalid. `xml_escape` is a [Jekyll extension of Liquid](https://github.com/mojombo/jekyll/blob/master/lib/jekyll/filters.rb#L59-L72) to safely escape values.
Using straight Liquid, this could also be done with:
``` html
<title type="html">
{{ post.title | escape
| replace:'&','&amp;'
| replace:'<','&lt;'
| replace:'>','&gt;' }}
</title>
```
(Note, `type=html` and then the [additional XML escaping](http://atomenabled.org/developers/syndication/#text).)

Escape post.title in atom.xml

---

_layouts/default.html

Hi,
This patch fix the error: `Error: A charset attribute on a meta element found after the first 1024 bytes.`
cf https://validator.nu/?doc=https%3A%2F%2Fblog.rubygems.org%2F&showsource=yes
Cheers;
Laurent

Move meta charset on top of head element

---

_posts/2021-02-09-january-rubygems-update.md

Add RubyGems January 2021 Updates.
Hi, @deivid-rodriguez  and @sonalkr132 can you help review to ensure I covered work done in January. Thanks!

Add RubyGems January Update

---

_posts/2021-09-04-august-rubygems-updates.md
_posts/2021-09-10-august-rubygems-updates.md

Hello, @deivid-rodriguez and @sonalkr132 can you kindly help me go over this draft to ensure I covered the work done in August. I didn't get any update on Slack for the RubyGems section so if there's any additional thing you want me to add please let me know.
Thanks!

RubyGems Monthly Update - August

---

_posts/2022-06-13-making-packages-more-secure.md

From https://github.com/rubygems/rubygems.org/pull/3089#discussion_r898305452, it's been pointed out that we should clarify the enforcement download threshold in the blog post.

Clarify enforcement threshold in June MFA blog post

---

_posts/2022-08-08-july-rubygems-updates.md

Draft update for July 2022.
Hi @deivid-rodriguez can you help review the updates from last month's work. thank you!

Add RubyGems Updates July 2022

---

stylesheets/application.css

The monospace is  too spaced out and irritating to read, and this css fixes that.
Before:
After:

decrease spacing between words in code segments

---

_posts/2022-08-22-mfa-ui-only-removed.md

Part of [Deprecate ui_only and migrate users to ui_and_gem_signin](https://github.com/rubygems/rubygems.org/issues/2968), an effort to remove the `UI only` MFA level for Rubygems which has been deemed insecure.
Users can no longer change their MFA level to UI Only after https://github.com/rubygems/rubygems.org/pull/3084 was merged about a month ago, and this blog post explains why.
I picked the following dates somewhat arbitrarily and would like to know if they are fine:
July 26th for the blog post date
August 26th for the day of `UI only` -> `UI and gem signin` migration
When this blog post is out, it could be linked in this guide PR too: https://github.com/rubygems/guides/pull/311

Add MFA "UI only" removal blog post

---

_posts/2022-08-22-mfa-ui-only-removed.md

I seemed to have forgotten to wrap these MFA levels in backticks, and this PR fixes it.

Make mfa levels all backticked in UI Only removal blog post

---

_posts/2022-12-12-november-rubygems-updates.md
_posts/2022-12-15-november-rubygems-updates.md

RubyGems update roundup for November 2022.
Hi @deivid-rodriguez, can you help review this month's update to ensure I accurately captured the work done in November? We also added a contributor appreciation section. Let me know if you have any feedback on it.

Add Monthly Update for November 2022

---

_posts/2022-12-21-introducing-hardware-security-token-and-passkey-support.md

Making an announcement post of the new support for Hardware Security Keys & Passkey support in RubyGems.org.

Add "Introducing Hardware Security Token & Passkey support" blog post

---

_layouts/default.html

- Update header menu links to more closely match rubygems.org, as outlined here:
[**RubyGems features:** UI Issue: Make Header Menu Consistent on Blog/Guides SubSites](https://github.com/orgs/rubygems/projects/6/views/1?pane=issue&itemId=18722655)
- Change `http://` nav links to `https://`

Update header menu

---

_posts/2023-04-03-security-device-cli-support.md
_posts/2023-04-11-security-device-cli-support.md

As the WebAuthn on the CLI feature https://github.com/rubygems/rubygems.org/issues/3453 approaches completion, here's a draft of a blog post for release.

Add blog post to introduce WebAuthn CLI support 

---

_posts/2023-04-18-march-rubygems-updates.md

RubyGems update roundup for March 2023.
Hi @deivid-rodriguez, can you help review this month's update to ensure I accurately captured the work done last month?

Publish RubyGems Monthly Updates for March 2023

---

_posts/2024-03-15-password-reset-vulnerability.md

@martinemde does this change make sense?

Tiny fix for 2024-03-15-password-reset-vulnerability.md.

---

_posts/2024-05-30-bundler-auto-install-just-got-a-whole-lot-better.md

After a rave review of rubygems/rubygems#6561 by Ngan Pham, I asked if they were interested in writing a blog post and this is it!
Thanks Ngan!

Auto-install blog post by guest author Ngan Pham

---

stylesheets/application.css

Code pre blocks look strange when spaces are not the same size as the letters

---

_posts/2024-11-07-maintainer-role.md

This PR is adding our announcement for the Maintainer Role to rubygems.org

Add maintainer role

---

_posts/2024-12-16-3.6.0-released.md

Changes `REAME` → `README` in the 16 Dec 2024 3.6.0 Released post at https://blog.rubygems.org/2024/12/16/3.6.0-released.html to better describe the effect of rubygems/rubygems#8262.
Proposed alongside rubygems/rubygems#8638.
---
Cheers, and thank you!

Fix typo in 16 Dec 2024 3.6.0 Released post

---

_posts/2025-05-20-april-rubygems-updates.md
stylesheets/scss/type.scss

- there is probably wrong syntax for bold parts, I tried to fix
- seems bold does nothing now since font-weight is wrongly set to normal
- fixed also Clickhouse -> ClickHouse

Few random tweaks for April 2025

---

_posts/2025-08-08-malicious-gems-removal.md

Publish blog post on team's response to malicious gems report.

Update on malicious gems removal

---

_posts/2022-01-19-rubygems-adoptions.md

I recalled this gem adoption feature today and spent some time trying to locate it, before ending up searching the website code to discover it was removed.
Adding a header to state so would have helped me, maybe it will help other people in the future :smile: ?

Update the gem adoption article to indicate it is gone
